version: "3.9"
services:
  backend:
    build: ./backend
    container_name: combination-backend
    ports:
      - "8080:8080"
    

  frontend:
    build: ./frontend
    container_name: combination-frontend
    environment:
      - REACT_APP_API_URL=http://backend:8080
    ports:
      - "3000:80"
    depends_on:
      - backend

